import type { Challenge } from './types';

export const motionChallenges: Challenge[] = [
  {
    id: 'motion-01',
    title: 'Start of line',
    description: 'Move to the beginning of the line, then change debug to trace.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'debugLogger.info("ready");',
    targetContent: 'traceLogger.info("ready");',
    initialCursor: { line: 0, column: 22 },
    concepts: ['0', 'cw'],
    hints: [
      'The cursor starts near the end of the line.',
      'Move to the beginning before changing the first word.',
      'Try `0cwtrace`.',
    ],
    intendedMove: '0cw',
  },
  {
    id: 'motion-02',
    title: 'End of line',
    description: 'Append the missing semicolon.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const retries = 3',
    targetContent: 'const retries = 3;',
    initialCursor: { line: 0, column: 0 },
    concepts: ['$', 'a'],
    hints: [
      'The change belongs at the end of the line.',
      'Jump to the line end before appending.',
      'Try `$a;`.',
    ],
    intendedMove: '$a',
  },
  {
    id: 'motion-03',
    title: 'Find the flag',
    description: 'Jump to enabled and change it to disabled.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const enabled = flags.beta;',
    targetContent: 'const disabled = flags.beta;',
    initialCursor: { line: 0, column: 0 },
    concepts: ['f', 'cw'],
    hints: [
      'The word you need is later on the same line.',
      'Find the start of `enabled`, then change it.',
      'Try `fe` then `cwdisabled`.',
    ],
    intendedMove: 'fecw',
  },
  {
    id: 'motion-04',
    title: 'Next word',
    description: 'Jump to cache and change it to store.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const cache = createCache();',
    targetContent: 'const store = createCache();',
    initialCursor: { line: 0, column: 0 },
    concepts: ['w', 'cw'],
    hints: [
      'The first word is not the one you need to change.',
      'Jump to the next word, then change it.',
      'Try `wcwstore`.',
    ],
    intendedMove: 'wcw',
  },
];
