import type { Challenge } from './types';

export const motionChallenges: Challenge[] = [
  {
    id: 'motion-01',
    title: 'Start of line',
    description: 'Move to the beginning of the line, then change debug to trace.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'debugLogger.info("ready");',
    targetContent: 'traceLogger.info("ready");',
    initialCursor: { line: 0, column: 22 },
    concepts: ['0', 'cw'],
    hints: [
      'The cursor starts near the end of the line.',
      'Move to the beginning before changing the first word.',
      'Try `0cwtrace`.',
    ],
    intendedMove: '0cw',
  },
  {
    id: 'motion-02',
    title: 'End of line',
    description: 'Append the missing semicolon.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const retries = 3',
    targetContent: 'const retries = 3;',
    initialCursor: { line: 0, column: 0 },
    concepts: ['$', 'a'],
    hints: [
      'The change belongs at the end of the line.',
      'Jump to the line end before appending.',
      'Try `$a;`.',
    ],
    intendedMove: '$a',
  },
  {
    id: 'motion-03',
    title: 'Find the flag',
    description: 'Jump to enabled and change it to disabled.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const enabled = flags.beta;',
    targetContent: 'const disabled = flags.beta;',
    initialCursor: { line: 0, column: 0 },
    concepts: ['f', 'cw'],
    hints: [
      'The word you need is later on the same line.',
      'Find the start of `enabled`, then change it.',
      'Try `fe` then `cwdisabled`.',
    ],
    intendedMove: 'fecw',
  },
  {
    id: 'motion-04',
    title: 'Next word',
    description: 'Jump to cache and change it to store.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'const cache = createCache();',
    targetContent: 'const store = createCache();',
    initialCursor: { line: 0, column: 0 },
    concepts: ['w', 'cw'],
    hints: [
      'The first word is not the one you need to change.',
      'Jump to the next word, then change it.',
      'Try `wcwstore`.',
    ],
    intendedMove: 'wcw',
  },
  {
    id: 'motion-05',
    title: 'Previous word',
    description: 'Jump back to retries and change it to attempts.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'failed retries = 0;',
    targetContent: 'failed attempts = 0;',
    initialCursor: { line: 0, column: 15 },
    concepts: ['b', 'cw'],
    hints: [
      'The cursor starts on `=`, not on the word to change.',
      'Jump back one word, then change it.',
      'Try `bcwattempts`.',
    ],
    intendedMove: 'bcw',
  },
  {
    id: 'motion-06',
    title: 'Till the hyphen',
    description: 'Change legacy to current, keeping the -name suffix.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'label: "legacy-name";',
    targetContent: 'label: "current-name";',
    initialCursor: { line: 0, column: 8 },
    concepts: ['t', 'c'],
    hints: [
      'You only need to replace the part before the hyphen.',
      'Change until the next `-`, then type the new prefix.',
      'Try `ct-current`.',
    ],
    intendedMove: 'ct-',
  },
  {
    id: 'motion-07',
    title: 'Find backward',
    description: 'Jump back to true and change it to false.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'retryOnFailure(true)',
    targetContent: 'retryOnFailure(false)',
    initialCursor: { line: 0, column: 19 },
    concepts: ['F', 'cw'],
    hints: [
      'The word you need is earlier on the same line.',
      'Find backward to the start of `true`, then change it.',
      'Try `Ft` then `cwfalse`.',
    ],
    intendedMove: 'Ftcw',
  },
  {
    id: 'motion-08',
    title: 'End of word',
    description: 'Jump to the end of user and append Id.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'return user;',
    targetContent: 'return userId;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['e', 'a'],
    hints: [
      'You need to add a suffix, not replace the word.',
      'Jump to the last character of `user`, then append.',
      'Try `eaId`.',
    ],
    intendedMove: 'ea',
  },
  {
    id: 'motion-09',
    title: 'Till backward',
    description: 'Drop the config/ prefix and keep the filename.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'open("config/app.json")',
    targetContent: 'open("app.json")',
    initialCursor: { line: 0, column: 13 },
    concepts: ['T', 'd'],
    hints: [
      'Keep the filename. Drop the directory prefix before it.',
      'Delete backward till after the opening quote.',
      'Try `dT"`.',
    ],
    intendedMove: 'dT"',
  },
  {
    id: 'motion-10',
    title: 'Matching paren',
    description: 'Jump to the closing parenthesis and append a semicolon.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: 'save(user)',
    targetContent: 'save(user);',
    initialCursor: { line: 0, column: 4 },
    concepts: ['%', 'a'],
    hints: [
      'The cursor starts on the opening parenthesis.',
      'Jump to the matching parenthesis, then append after it.',
      'Try `%a;`.',
    ],
    intendedMove: '%a',
  },
  {
    id: 'motion-11',
    title: 'End of the file',
    description: 'The draft flag is below the fold. Jump to the last line and change draft to live.',
    category: 'motion',
    difficulty: 'medium',
    initialContent: [
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
      'const batchSize = 100;',
      'draft = true;',
    ].join('\n'),
    targetContent: [
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
      'const batchSize = 100;',
      'live = true;',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['G', 'cw'],
    hints: [
      'The word to change is not on the first screen.',
      'Jump to the last line, then change the first word.',
      'Try `Gcwlive`.',
    ],
    intendedMove: 'Gcw',
  },
  {
    id: 'motion-12',
    title: 'First non-blank',
    description: 'Skip the indent, then change debug to trace.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: '    debug = true;',
    targetContent: '    trace = true;',
    initialCursor: { line: 0, column: 16 },
    concepts: ['^', 'cw'],
    hints: [
      'The cursor starts at the end of an indented line.',
      '`0` would land on the spaces. Jump to the first non-blank, then change the word.',
      'Try `^cwtrace`.',
    ],
    intendedMove: '^cw',
  },
  {
    id: 'motion-13',
    title: 'Top of the file',
    description: 'Jump to the first line and change draft to final.',
    category: 'motion',
    difficulty: 'easy',
    initialContent: [
      'draft = true;',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
    ].join('\n'),
    targetContent: [
      'final = true;',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
    ].join('\n'),
    initialCursor: { line: 13, column: 0 },
    concepts: ['gg', 'cw'],
    hints: [
      'You start at the bottom. The word to change is on the first line.',
      'Jump to the top of the file, then change the word.',
      'Try `ggcwfinal`.',
    ],
    intendedMove: 'ggcw',
  },
];
