import type { Challenge } from './types';

export const operatorChallenges: Challenge[] = [
  {
    id: 'operator-01',
    title: 'Delete a log line',
    description: 'Delete the console.log statement.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: [
      'const response = await fetch(url);',
      'console.log(response);',
      'return response;',
    ].join('\n'),
    targetContent: [
      'const response = await fetch(url);',
      'return response;',
    ].join('\n'),
    initialCursor: { line: 1, column: 0 },
    concepts: ['dd'],
    hints: [
      'The whole current line should go away.',
      'Use a linewise delete.',
      'Try `dd`.',
    ],
    intendedMove: 'dd',
  },
  {
    id: 'operator-02',
    title: 'Change a word',
    description: 'Rename result to user.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return result.profile;',
    targetContent: 'return user.profile;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['cw'],
    hints: [
      'The cursor starts on the word to replace.',
      'Change the current word.',
      'Try `cwuser`.',
    ],
    intendedMove: 'cw',
  },
  {
    id: 'operator-03',
    title: 'Delete a word',
    description: 'Remove the unused identifier so the return is clean.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return unused result;',
    targetContent: 'return result;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['dw'],
    hints: [
      'The cursor starts on the word that should disappear.',
      'Delete the current word, including the space after it.',
      'Try `dw`.',
    ],
    intendedMove: 'dw',
  },
  {
    id: 'operator-04',
    title: 'Delete a WORD',
    description: 'Remove the first argument, including the comma.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'connect(legacyHost, backupHost);',
    targetContent: 'connect(backupHost);',
    initialCursor: { line: 0, column: 8 },
    concepts: ['dW'],
    hints: [
      'A WORD stops at whitespace, so it includes the comma.',
      'Delete the WORD under the cursor.',
      'Try `dW`.',
    ],
    intendedMove: 'dW',
  },
  {
    id: 'operator-05',
    title: 'Delete a character',
    description: 'Remove the stray comma before the closing parenthesis.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'items.push(next,);',
    targetContent: 'items.push(next);',
    initialCursor: { line: 0, column: 15 },
    concepts: ['x'],
    hints: [
      'The cursor starts on the extra character.',
      'Delete the character under the cursor.',
      'Try `x`.',
    ],
    intendedMove: 'x',
  },
  {
    id: 'operator-06',
    title: 'Delete to end of line',
    description: 'Drop the trailing comment after the return.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return user.profile; // TODO: drop this',
    targetContent: 'return user.profile;',
    initialCursor: { line: 0, column: 20 },
    concepts: ['D'],
    hints: [
      'The cursor starts just after the statement you want to keep.',
      'Delete from the cursor to the end of the line.',
      'Try `D`.',
    ],
    intendedMove: 'D',
  },
  {
    id: 'operator-07',
    title: 'Change to end of line',
    description: 'Replace the rest of the return so it yields user.id.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return user.profile;',
    targetContent: 'return user.id;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['C'],
    hints: [
      'Everything from the cursor to the end of the line should be replaced.',
      'Change to the end of the line, then type the new return value.',
      'Try `Cuser.id;`.',
    ],
    intendedMove: 'C',
  },
  {
    id: 'operator-08',
    title: 'Delete till a quote',
    description: 'Drop the path expression and keep the quoted filename.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'open(path + "backup.json")',
    targetContent: 'open("backup.json")',
    initialCursor: { line: 0, column: 5 },
    concepts: ['dt'],
    hints: [
      'Keep the quoted filename. Drop everything before it.',
      'Delete until the next `"`, leaving that quote in place.',
      'Try `dt"`.',
    ],
    intendedMove: 'dt"',
  },
  {
    id: 'operator-09',
    title: 'Replace a character',
    description: 'Fix the port so it ends in 0, not 1.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'listen(8081);',
    targetContent: 'listen(8080);',
    initialCursor: { line: 0, column: 10 },
    concepts: ['r'],
    hints: [
      'The cursor starts on the wrong digit.',
      'Replace the character under the cursor without entering Insert mode for a full edit.',
      'Try `r0`.',
    ],
    intendedMove: 'r',
  },
  {
    id: 'operator-10',
    title: 'Change the whole line',
    description: 'Replace the entire return with return null.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return legacyHandler(event);',
    targetContent: 'return null;',
    initialCursor: { line: 0, column: 0 },
    concepts: ['cc'],
    hints: [
      'The whole line should be rewritten.',
      'Change the current line, then type the new statement.',
      'Try `ccreturn null;`.',
    ],
    intendedMove: 'cc',
  },
  {
    id: 'operator-11',
    title: 'Delete a leftover log',
    description: 'A debug log was left at the bottom. Jump there and delete that line.',
    category: 'operator',
    difficulty: 'medium',
    initialContent: [
      'const user = req.user;',
      'const path = req.path;',
      'const method = req.method;',
      'const startedAt = Date.now();',
      'const requestId = req.id;',
      'const session = req.session;',
      'const locale = req.locale ?? "en";',
      'const payload = req.body;',
      'const query = req.query;',
      'const flags = loadFlags(user);',
      'const result = route(path, method, payload, query, flags);',
      'track(requestId, Date.now() - startedAt);',
      'respond(result, session, locale);',
      'console.log(req);',
    ].join('\n'),
    targetContent: [
      'const user = req.user;',
      'const path = req.path;',
      'const method = req.method;',
      'const startedAt = Date.now();',
      'const requestId = req.id;',
      'const session = req.session;',
      'const locale = req.locale ?? "en";',
      'const payload = req.body;',
      'const query = req.query;',
      'const flags = loadFlags(user);',
      'const result = route(path, method, payload, query, flags);',
      'track(requestId, Date.now() - startedAt);',
      'respond(result, session, locale);',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['G', 'dd'],
    hints: [
      'The leftover log is the last line, below the fold.',
      'Jump to the end of the file, then delete the current line.',
      'Try `Gdd`.',
    ],
    intendedMove: 'Gdd',
  },
  {
    id: 'operator-12',
    title: 'Swap two characters',
    description: 'form is a typo for from. Swap the two letters.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'import form "./auth";',
    targetContent: 'import from "./auth";',
    initialCursor: { line: 0, column: 8 },
    concepts: ['x', 'p'],
    hints: [
      'The cursor starts on the first of two swapped letters.',
      'Delete the character, then put it after the next one.',
      'Try `xp`.',
    ],
    intendedMove: 'xp',
  },
];
