import type { Challenge } from './types';

export const operatorChallenges: Challenge[] = [
  {
    id: 'operator-01',
    title: 'Delete a log line',
    description: 'Delete the console.log statement.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: [
      'const response = await fetch(url);',
      'console.log(response);',
      'return response;',
    ].join('\n'),
    targetContent: [
      'const response = await fetch(url);',
      'return response;',
    ].join('\n'),
    initialCursor: { line: 1, column: 0 },
    concepts: ['dd'],
    hints: [
      'The whole current line should go away.',
      'Use a linewise delete.',
      'Try `dd`.',
    ],
    intendedMove: 'dd',
  },
  {
    id: 'operator-02',
    title: 'Change a word',
    description: 'Rename result to user.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return result.profile;',
    targetContent: 'return user.profile;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['cw'],
    hints: [
      'The cursor starts on the word to replace.',
      'Change the current word.',
      'Try `cwuser`.',
    ],
    intendedMove: 'cw',
  },
  {
    id: 'operator-03',
    title: 'Delete a word',
    description: 'Remove the unused identifier so the return is clean.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'return unused result;',
    targetContent: 'return result;',
    initialCursor: { line: 0, column: 7 },
    concepts: ['dw'],
    hints: [
      'The cursor starts on the word that should disappear.',
      'Delete the current word, including the space after it.',
      'Try `dw`.',
    ],
    intendedMove: 'dw',
  },
  {
    id: 'operator-04',
    title: 'Delete a WORD',
    description: 'Remove the first argument, including the comma.',
    category: 'operator',
    difficulty: 'easy',
    initialContent: 'connect(legacyHost, backupHost);',
    targetContent: 'connect(backupHost);',
    initialCursor: { line: 0, column: 8 },
    concepts: ['dW'],
    hints: [
      'A WORD stops at whitespace, so it includes the comma.',
      'Delete the WORD under the cursor.',
      'Try `dW`.',
    ],
    intendedMove: 'dW',
  },
];
