import type { Challenge } from './types';

export const replaceChallenges: Challenge[] = [
  {
    id: 'replace-01',
    title: 'Substitute on the line',
    description: 'Rename colour to color on this line only.',
    category: 'replace',
    difficulty: 'easy',
    initialContent: 'const colour = "navy";',
    targetContent: 'const color = "navy";',
    initialCursor: { line: 0, column: 0 },
    concepts: [':s'],
    hints: [
      'You do not need to move. Substitute on the current line.',
      'Open the command line and replace the first colour.',
      'Try `:s/colour/color` then Enter.',
    ],
    intendedMove: ':s/colour/color',
  },
  {
    id: 'replace-02',
    title: 'Substitute every match',
    description: 'Rename every colour to color in the file.',
    category: 'replace',
    difficulty: 'medium',
    initialContent: [
      'const colour = "navy";',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const fallback = colour;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const border = colour;',
      'return colour;',
    ].join('\n'),
    targetContent: [
      'const color = "navy";',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const fallback = color;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const border = color;',
      'return color;',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: [':%s', 'g'],
    hints: [
      'Several colours sit below the fold. Do not change them one by one.',
      'Run a global substitute across the whole file.',
      'Try `:%s/colour/color/g` then Enter.',
    ],
    intendedMove: ':%s/colour/color/g',
  },
];
