import type { Challenge } from './types';

export const searchChallenges: Challenge[] = [
  {
    id: 'search-01',
    title: 'Search for a word',
    description: 'Search for legacy and change it to current.',
    category: 'search',
    difficulty: 'medium',
    initialContent: [
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
      'const adapter = legacy;',
    ].join('\n'),
    targetContent: [
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const queue = "jobs";',
      'const workers = 4;',
      'const adapter = current;',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['/', 'cw'],
    hints: [
      'The word is below the fold. Search for it instead of scrolling by hand.',
      'Type a search, confirm it, then change the match.',
      'Try `/legacy` then Enter, then `cwcurrent`.',
    ],
    intendedMove: '/legacycw',
  },
  {
    id: 'search-02',
    title: 'Next search match',
    description: 'The first beta should stay. Jump to the next one and change it to stable.',
    category: 'search',
    difficulty: 'medium',
    initialContent: [
      'const channel = "beta";',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const release = "beta";',
    ].join('\n'),
    targetContent: [
      'const channel = "beta";',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'const release = "stable";',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['/', 'n', 'ci"'],
    hints: [
      'Search finds the first beta. That one should stay.',
      'Advance to the next match, then change the quoted text.',
      'Try `/beta` then Enter, `n`, then `ci"stable`.',
    ],
    intendedMove: '/betanci"',
  },
  {
    id: 'search-03',
    title: 'Search the word under the cursor',
    description: 'Jump to the next experimental and change it to stable.',
    category: 'search',
    difficulty: 'medium',
    initialContent: [
      'const flag = experimental;',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'return experimental;',
    ].join('\n'),
    targetContent: [
      'const flag = experimental;',
      'const host = "0.0.0.0";',
      'const port = 8080;',
      'const timeout = 5000;',
      'const retries = 3;',
      'const region = "ap-southeast-1";',
      'const bucket = "uploads";',
      'const cacheTtl = 60;',
      'const maxUpload = 12;',
      'const logLevel = "info";',
      'const metrics = true;',
      'const tracing = false;',
      'return stable;',
    ].join('\n'),
    initialCursor: { line: 0, column: 13 },
    concepts: ['*', 'cw'],
    hints: [
      'The cursor starts on experimental. Search for that word without typing it.',
      'Jump to the next match, then change it.',
      'Try `*` then `cwstable`.',
    ],
    intendedMove: '*cw',
  },
];
