import type { Challenge } from './types';

export const textObjectChallenges: Challenge[] = [
  {
    id: 'text-object-01',
    title: 'Change quoted text',
    description: 'Change "production" to "staging".',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'const environment = "production";',
    targetContent: 'const environment = "staging";',
    initialCursor: { line: 0, column: 22 },
    concepts: ['change', 'text-object', 'quote'],
    hints: [
      'Think about text objects.',
      'Change the contents inside the quotes.',
      'Try `ci"`.',
    ],
    intendedMove: 'ci"',
  },
  {
    id: 'text-object-02',
    title: 'Clear arguments',
    description: 'Remove all arguments from the function call.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'calculatePrice(basePrice, tax, discount)',
    targetContent: 'calculatePrice()',
    initialCursor: { line: 0, column: 21 },
    concepts: ['change', 'text-object', 'parentheses'],
    hints: [
      'The arguments are inside parentheses.',
      'Change the inside of the parentheses to nothing.',
      'Try `ci(`.',
    ],
    intendedMove: 'ci(',
  },
  {
    id: 'text-object-03',
    title: 'Replace an object value',
    description: 'Change the timeout value to 5000.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'const options = { timeout: 3000, retries: 2 };',
    targetContent: 'const options = { timeout: 5000, retries: 2 };',
    initialCursor: { line: 0, column: 28 },
    concepts: ['change', 'word'],
    hints: [
      'The cursor starts on the value to replace.',
      'Change the current word or number.',
      'Try `ciw5000`.',
    ],
    intendedMove: 'ciw',
  },
  {
    id: 'text-object-04',
    title: 'Change a block',
    description: 'Replace the if-body with return null.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'if (!user) { throw new Error("missing"); }',
    targetContent: 'if (!user) { return null; }',
    initialCursor: { line: 0, column: 13 },
    concepts: ['ci{', 'text-object'],
    hints: [
      'The body you need to replace is inside the braces.',
      'Change the contents inside the curly braces.',
      'Try `ci{` then ` return null; `.',
    ],
    intendedMove: 'ci{',
  },
  {
    id: 'text-object-05',
    title: 'Delete a word from inside',
    description: 'Remove unused even though the cursor is in the middle of it.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'return unused result;',
    targetContent: 'return result;',
    initialCursor: { line: 0, column: 9 },
    concepts: ['daw', 'text-object'],
    hints: [
      'The cursor starts in the middle of the extra word.',
      '`dw` from here would leave a prefix behind. Delete a whole word.',
      'Try `daw`.',
    ],
    intendedMove: 'daw',
  },
  {
    id: 'text-object-06',
    title: 'Change around quotes',
    description: 'Replace the quoted status, including the quotes, with ready.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'status: "idle";',
    targetContent: 'status: ready;',
    initialCursor: { line: 0, column: 10 },
    concepts: ['ca"', 'text-object'],
    hints: [
      'The quotes should disappear with the old word.',
      'Change around the quoted text, not just inside it.',
      'Try `ca"ready`.',
    ],
    intendedMove: 'ca"',
  },
  {
    id: 'text-object-07',
    title: 'Change single-quoted text',
    description: "Change 'dark' to 'light'.",
    category: 'text-object',
    difficulty: 'easy',
    initialContent: "const mode = 'dark';",
    targetContent: "const mode = 'light';",
    initialCursor: { line: 0, column: 15 },
    concepts: ["ci'", 'text-object'],
    hints: [
      'Single quotes work like double quotes for text objects.',
      'Change the contents inside the single quotes.',
      "Try `ci'light`.",
    ],
    intendedMove: "ci'",
  },
  {
    id: 'text-object-08',
    title: 'Change a quoted value off-screen',
    description: 'Jump to the last line and change "production" to "staging".',
    category: 'text-object',
    difficulty: 'medium',
    initialContent: [
      'const cacheKey = `user:${id}`;',
      'const cached = cache.get(cacheKey);',
      'const row = db.users.findById(id);',
      'const profile = row?.profile;',
      'const email = row?.email;',
      'const roles = row?.roles ?? [];',
      'const locale = row?.locale ?? "en";',
      'const lastSeen = row?.lastSeen;',
      'const createdAt = row?.createdAt;',
      'const updatedAt = row?.updatedAt;',
      'const plan = row?.plan ?? "free";',
      'const seats = row?.seats ?? 1;',
      'const environment = "production";',
    ].join('\n'),
    targetContent: [
      'const cacheKey = `user:${id}`;',
      'const cached = cache.get(cacheKey);',
      'const row = db.users.findById(id);',
      'const profile = row?.profile;',
      'const email = row?.email;',
      'const roles = row?.roles ?? [];',
      'const locale = row?.locale ?? "en";',
      'const lastSeen = row?.lastSeen;',
      'const createdAt = row?.createdAt;',
      'const updatedAt = row?.updatedAt;',
      'const plan = row?.plan ?? "free";',
      'const seats = row?.seats ?? 1;',
      'const environment = "staging";',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['G', 'ci"'],
    hints: [
      'The quoted value sits on the last line, below the fold.',
      'Jump to the last line, then change inside the quotes.',
      'Try `Gci"staging`.',
    ],
    intendedMove: 'Gci"',
  },
  {
    id: 'text-object-09',
    title: 'Change inside brackets',
    description: 'Replace the list contents with id.',
    category: 'text-object',
    difficulty: 'easy',
    initialContent: 'const ids = [1, 2, 3];',
    targetContent: 'const ids = [id];',
    initialCursor: { line: 0, column: 16 },
    concepts: ['ci[', 'text-object'],
    hints: [
      'The cursor starts inside the square brackets.',
      'Change the contents inside the brackets, not the brackets themselves.',
      'Try `ci[id`.',
    ],
    intendedMove: 'ci[',
  },
];
