import type { Challenge } from './types';

export const visualChallenges: Challenge[] = [
  {
    id: 'visual-01',
    title: 'Change a selected word',
    description: 'Select startJob visually, then change it to runJob.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: [
      'if (isReady) {',
      '  return startJob();',
      '}',
    ].join('\n'),
    targetContent: [
      'if (isReady) {',
      '  return runJob();',
      '}',
    ].join('\n'),
    initialCursor: { line: 1, column: 9 },
    concepts: ['visual', 'change'],
    hints: [
      'The word to change is under the cursor.',
      'Enter Visual mode and extend to the end of the word.',
      'Try `vecrunJob`.',
    ],
    intendedMove: 'vec',
  },
  {
    id: 'visual-02',
    title: 'Delete a visual line',
    description: 'Visually select the deprecated comment and delete it.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: [
      'function start() {',
      '  // deprecated path',
      '  return boot();',
      '}',
    ].join('\n'),
    targetContent: [
      'function start() {',
      '  return boot();',
      '}',
    ].join('\n'),
    initialCursor: { line: 1, column: 2 },
    concepts: ['V', 'd'],
    hints: [
      'The whole current line should go away.',
      'Enter Visual-Line mode, then delete the selection.',
      'Try `Vd`.',
    ],
    intendedMove: 'Vd',
  },
  {
    id: 'visual-03',
    title: 'Change inside quotes visually',
    description: 'Select the quoted text visually, then change it to staging.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: 'const environment = "production";',
    targetContent: 'const environment = "staging";',
    initialCursor: { line: 0, column: 22 },
    concepts: ['v', 'i"', 'c'],
    hints: [
      'The cursor starts inside the quotes.',
      'Visually select the inner quoted text, then change it.',
      'Try `vi"cstaging`.',
    ],
    intendedMove: 'vi"c',
  },
  {
    id: 'visual-04',
    title: 'Change a word from inside',
    description: 'Visually select the whole word from the middle, then change it to attemptCount.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: 'let retryCount = 0;',
    targetContent: 'let attemptCount = 0;',
    initialCursor: { line: 0, column: 8 },
    concepts: ['v', 'iw', 'c'],
    hints: [
      'The cursor starts in the middle of the word.',
      'Visually select the inner word, then change it.',
      'Try `viwcattemptCount`.',
    ],
    intendedMove: 'viwc',
  },
  {
    id: 'visual-05',
    title: 'Change inside parens visually',
    description: 'Visually select the arguments, then change them to 1, 2.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: 'sum(left, right)',
    targetContent: 'sum(1, 2)',
    initialCursor: { line: 0, column: 3 },
    concepts: ['v', 'i(', 'c'],
    hints: [
      'The cursor starts on the opening parenthesis.',
      'Visually select inside the parentheses, then change the selection.',
      'Try `vi(c1, 2`.',
    ],
    intendedMove: 'vi(c',
  },
  {
    id: 'visual-06',
    title: 'Delete leftover calls',
    description: 'Three unused calls sit at the bottom. Jump there, select them visually, and delete them.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: [
      'loadConfig();',
      'connectDb();',
      'connectCache();',
      'bindRoutes();',
      'registerHooks();',
      'startWorkers();',
      'startScheduler();',
      'startHttp();',
      'warmCache();',
      'reportReady();',
      'unused();',
      'unused();',
      'unused();',
    ].join('\n'),
    targetContent: [
      'loadConfig();',
      'connectDb();',
      'connectCache();',
      'bindRoutes();',
      'registerHooks();',
      'startWorkers();',
      'startScheduler();',
      'startHttp();',
      'warmCache();',
      'reportReady();',
    ].join('\n'),
    initialCursor: { line: 0, column: 0 },
    concepts: ['G', 'V', 'd'],
    hints: [
      'The unused calls are the last three lines, below the fold.',
      'Jump to the last line, extend Visual-Line up through the unused calls, then delete.',
      'Try `GVkkd`.',
    ],
    intendedMove: 'GVkkd',
  },
  {
    id: 'visual-07',
    title: 'Change inside braces visually',
    description: 'Visually select the brace body, then change it to break.',
    category: 'visual',
    difficulty: 'medium',
    initialContent: 'while (busy) { wait(); }',
    targetContent: 'while (busy) { break; }',
    initialCursor: { line: 0, column: 15 },
    concepts: ['v', 'i{', 'c'],
    hints: [
      'The cursor starts inside the braces.',
      'Visually select the inner brace text, then change it.',
      'Try `vi{c` then ` break; `.',
    ],
    intendedMove: 'vi{c',
  },
];
